In [1]:
## Num PY

# A - Range, not arrange
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype.name)
print(a.itemsize)
print(a.size)
print(type(a))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int32
4
15
<class 'numpy.ndarray'>


In [4]:
d = np.ones( (3,4) )
print(d) 


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:

# 2 arrays
e = np.ones( (2,3,4), dtype=np.int16 ) 
print(e)

f = np.empty( (2,3) )  
print(f)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[7.2e-322 0.0e+000 0.0e+000]
 [0.0e+000 0.0e+000 0.0e+000]]


In [6]:
g = np.arange( 10, 31, 5 )
print(g)

[10 15 20 25 30]


In [8]:
h = np.linspace(10, 30, 9 ) 
print(h)

[10.  12.5 15.  17.5 20.  22.5 25.  27.5 30. ]


In [10]:
e = np.ones( (4,3,4), dtype=np.int16 ) 
print(e)


[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [11]:
import numpy as np
a = np.array( [20,30,40,50] )
b = np.array( [30,40,30,10] )

c = a-b
print(c)


c = b**2
print(c)

c = 10*np.sin(a)
print(c)

# elementwise
x = a*b
print(x)

[-10 -10  10  40]
[ 900 1600  900  100]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ 600 1200 1200  500]


In [13]:
import numpy as np
a = np.array( [20,30,40,50] )
b = np.array( [30,40,30,10] )

c = a-b
print(c)

[-10 -10  10  40]


In [14]:
c=b**2
print(c)

[ 900 1600  900  100]


In [15]:
c=10*np.sin(a)
print(c)

[ 9.12945251 -9.88031624  7.4511316  -2.62374854]


In [16]:
c=np.sin(a)
print(c)

[ 0.91294525 -0.98803162  0.74511316 -0.26237485]


[[3.  3.5]
 [3.2 3.6]]
[[-9.    8.75]
 [ 8.   -7.5 ]]
[118.4 135.2]
[16. 22.]


In [18]:
#limear algebra equation
A = np.array( [ [3,-1,2], [2,-2,3],[4,1,4] ], dtype=float)
#inverse
Ainv = np.linalg.inv(A)
C =  np.array( [[ 8],[2],[9] ])
r = np.dot(Ainv,C)
print(r)
x = np.linalg.solve(A,C) 
print(x)

[[ 3.94117647]
 [ 0.29411765]
 [-1.76470588]]
[[ 3.94117647]
 [ 0.29411765]
 [-1.76470588]]


In [19]:
a = np.array([5,2,6,2,7,5,6,8,2,9]) 
u = np.unique(a) 
print(u)

[2 5 6 7 8 9]


In [20]:
import scipy.special as special
result = integrate.quad(lambda x: special.jv(2.5,x), 0, 4.5)
print(result)

NameError: name 'integrate' is not defined

In [21]:
from numpy import poly1d
p = poly1d([3,4,5])
print(p*p)

   4      3      2
9 x + 24 x + 46 x + 40 x + 25


In [22]:
# Integration equation
import scipy.integrate as integrate
import scipy.special as special
result = integrate.quad(lambda x: special.jv(2.5,x), 0, 4.5)
print(result)

(1.1178179380783244, 7.866317216380707e-09)


In [23]:
a = np.array([1,2,3,4,5]) 
np.save('outfile',a)

b = np.load('outfile.npy') 
print (b)

np.savetxt('out.txt',a) 
b = np.loadtxt('out.txt') 
print(b)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [24]:
np.random.rand(3,2)


array([[0.81764761, 0.09481766],
       [0.34024789, 0.54094362],
       [0.08543257, 0.55821699]])

In [26]:
np.random.randn(3,2)

array([[ 0.50604804, -0.22520948],
       [-0.08093016,  0.04030399],
       [ 1.25797519, -0.37803988]])

In [27]:
np.random.randint(5, size=(2, 4))

array([[3, 2, 1, 3],
       [3, 0, 2, 1]])

In [28]:
np.random.randint(20,100, size=(2, 4))

array([[56, 72, 36, 31],
       [32, 37, 72, 96]])

In [29]:
# shuffle
arr = np.arange(9).reshape((3, 3))
print(arr)
np.random.shuffle(arr)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [0 1 2]
 [3 4 5]]
